jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SECRET_1 }}   # <--- Add this line

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Configure Git identity
        run: |
          git config user.name "mdtariqeahmad"
          git config user.email "mdtariqeahmad@users.noreply.github.com"

      - name: Sync LeetCode
        env:
          LEETCODE_SESSION: ${{ secrets.SECRET_2 }}
          LEETCODE_CSRF_TOKEN: ${{ secrets.SECRET_3 }}
        run: |
          python .github/scripts/sync_leetcode.py
