name: Sync LeetCode Solutions

on:
  workflow_dispatch: # Allows manual triggers anytime
  schedule:
    - cron: '30 18 * * *' # Runs daily at 12:00 AM IST (6:30 PM UTC)

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync LeetCode
        uses: joshcai/leetcode-sync@v1.8
        with:
          github-token: ${{ secrets.SECRET_1 }}
          leetcode-session: ${{ secrets.SECRET_2 }}
          destination-folder: ''
